### ISSUE TITLE
Captcha Train Param usage

### ISSUE THREAD

**Issue by RobertVeloso** [scnuhealthy/cnn_keras_captcha#4]
I'm having a hard time trying to use your project with phpcaptcha
How should I use the captcha_train.py?

img = get_image_from_file("data/"+imgs[i])
IndexError: list index out of range

**Comment by scnuhealthy** [comment]
As README illustrate, you should run the porgram "get_train_set.py" and generate the dataset first. The neural network will do nothing until you feed it with  great data.

**Comment by RobertVeloso** [comment]
So I ran the get_train_set.py, and the folder data now has 19.216 images. 
From the readme the next step would be captcha_train.py, but I can go any futher. I'm having this error: ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=1
My guess is that I need to fill the params when running the py script but i don't which flags to use
I'm sorry about my english, not native language.
Thanks anyway...

**Comment by scnuhealthy** [comment]
Firstly I am sorry about a miss in "capthcha_params.py". The WIDTH should be 160 and the HEIGHT should be 60. You can change them and make sure the size are identical to the size of your captcha that you generate.
However, I don't think the miss induces your problem. When you have run "get_train_set.py" exactly, the num of images should be 24000, if you have not altered the code. I guess there is something wrong with your environment. Maybe your backend of keras choose tensorflow. Theano is ok but I have not tested the code with tensorflow. Or you try upgrade your packages(e.g theano,keras) and make sure your keras can run normally.

**Comment by RobertVeloso** [comment]
Worked like a charm... captcha_params and amount of images on data folder was the problem.
Thanks, you're amazing!
![Uploading Sem título.png…]()

**Comment by RobertVeloso** [comment]
So, You can set the issue as closed. But could you give me some hints of how to use this project with 
PHP Captcha library: https://github.com/Gregwar/Captcha

**Comment by scnuhealthy** [comment]
Maybe I propose an another way to generate the captcha. Seriously, my code is mainly to recognize the captchas which are composed of letters and numbers.

**Comment by RobertVeloso** [comment]
Well, If you add another way, I'll be right here to test it. 👍
